### ISSUE TITLE
Update for Quarry release

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/DOLDataSDK-iOS#1]
Update SDK for DOL's v2 API

**Comment by neilneyman** [comment]
Currently still in progress.  Able to successfully query the API via HTTP request and receiving valid results, but crashing while returning  delegate with dictionaryresults to the sample program.
 `-[MasterViewController govDataRequest:didCompleteWithDictionaryResults:andResponseTime:]: unrecognized selector sent to instance 0x7fd0a3c97f60`

**Comment by MikePulsiferDOL** [comment]
Are you getting valid data back?  Have you tried inspecting it via NSLog prior to calling that method?

**Comment by neilneyman** [comment]
Yes, running through the debugger shows it's definitely getting the expected JSON string.  It's populating that into an NSDictionary and attempting to return that via a delegate -- just for some baffling reason it's crashing right at that point

**Comment by jfc3-dol** [comment]
Could it be some kind of character encoding issues?

I have seen when I was at the Army and pulling ARMY.MIL's RSS it broke because of character encoding issues. They had not set it up properly and some of the German words with their umlauts caused issues that caused the RSS feed to stop at the first word that had an umlauts. They fixed the issue once they knew they had it..

**Comment by MikePulsiferDOL** [comment]
Might want to try again using the just-updated sample app.  Newer version of Xcode wasn't liking how it was structured and some pieces were inexplicably missing.  I've tested it successfully against V1 a few minutes ago.

**Comment by adams-lisa** [comment]
Additional feature requested during UAT.  Feature added and verified during UAT.  Complete.  Closed
